name: "financo"

services:
  devcontainer:
    build:
      dockerfile: .devcontainer/devcontainer.Dockerfile
      context: .
      args:
        GO_VERSION: "1.23"
        ALPINE_VERSION: "3.20"
        NODE_VERSION: "20"
        NPM_VERSION: "latest"
        GO_AIR_VERSION: "latest"
        GO_GOOSE_VERSION: "latest"
        GO_DELVE_VERSION: "latest"
    user: vscode
    env_file: .env
    volumes:
      - .:/workspace:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis:
    image: redis:7.2
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: "financo"
      POSTGRES_PASSWORD: "local_dev"
      POSTGRES_DB: "financo_dev"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
