import {
  AmbulanceIcon,
  AppleIcon,
  ArmchairIcon,
  AtSignIcon,
  BabyIcon,
  BandageIcon,
  BanknoteIcon,
  BarcodeIcon,
  BatteryChargingIcon,
  BeanIcon,
  BedDoubleIcon,
  BedSingleIcon,
  BeefIcon,
  BellElectricIcon,
  BicepsFlexedIcon,
  BikeIcon,
  BinaryIcon,
  BinocularsIcon,
  BirdIcon,
  BitcoinIcon,
  BoneIcon,
  BookIcon,
  BookmarkIcon,
  BookOpenIcon,
  BrainIcon,
  BriefcaseIcon,
  BuildingIcon,
  BusFrontIcon,
  CableIcon,
  CakeIcon,
  CalculatorIcon,
  CandyIcon,
  CarFrontIcon,
  CarTaxiFrontIcon,
  CatIcon,
  CigaretteIcon,
  CircleParkingIcon,
  ClapperboardIcon,
  CloverIcon,
  CogIcon,
  CoinsIcon,
  ComputerIcon,
  ContainerIcon,
  CpuIcon,
  CreditCardIcon,
  CrossIcon,
  CrownIcon,
  DicesIcon,
  DogIcon,
  DropletIcon,
  DrumIcon,
  DrumstickIcon,
  DumbbellIcon,
  EarthIcon,
  EthernetPortIcon,
  FenceIcon,
  FilmIcon,
  FireExtinguisherIcon,
  FishIcon,
  FlowerIcon,
  FuelIcon,
  GamepadIcon,
  GlassesIcon,
  GlassWaterIcon,
  GlobeIcon,
  GraduationCapIcon,
  HammerIcon,
  HandCoinsIcon,
  HandPlatterIcon,
  HeadphonesIcon,
  HeartIcon,
  HeartPulseIcon,
  HeaterIcon,
  HospitalIcon,
  HouseIcon,
  IceCreamConeIcon,
  IdCardIcon,
  KeyRoundIcon,
  LandmarkIcon,
  LaptopIcon,
  LuggageIcon,
  MailIcon,
  MedalIcon,
  MegaphoneIcon,
  MicroscopeIcon,
  MicrowaveIcon,
  MicVocalIcon,
  MilkIcon,
  MonitorPlayIcon,
  MusicIcon,
  NotebookIcon,
  PackageIcon,
  PaintbrushVerticalIcon,
  PaintRollerIcon,
  PawPrintIcon,
  PcCaseIcon,
  PhoneIcon,
  PianoIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlaneIcon,
  PopcornIcon,
  RouterIcon,
  RulerIcon,
  SaladIcon,
  SandwichIcon,
  SchoolIcon,
  SearchIcon,
  ShieldIcon,
  ShipIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  ShowerHeadIcon,
  SirenIcon,
  SkullIcon,
  SmartphoneIcon,
  StethoscopeIcon,
  SwordIcon,
  SyringeIcon,
  TagIcon,
  TargetIcon,
  TentTreeIcon,
  TheaterIcon,
  TicketIcon,
  TicketsIcon,
  TrainFrontIcon,
  TreePalmIcon,
  TreesIcon,
  TrophyIcon,
  TvIcon,
  TvMinimalPlayIcon,
  UserIcon,
  UtensilsIcon,
  UtilityPoleIcon,
  VaultIcon,
  VenetianMaskIcon,
  VolleyballIcon,
  WalletCardsIcon,
  WalletMinimalIcon,
  WashingMachineIcon,
  WineIcon,
  ZapIcon
} from "lucide-react";
import { ICONS } from "~/modules/shared/types/icon";

export const icons = {
  [ICONS.credit_card]: <CreditCardIcon />,
  [ICONS.landmark]: <LandmarkIcon />,
  [ICONS.vault]: <VaultIcon />,
  [ICONS.banknote]: <BanknoteIcon />,
  [ICONS.hand_coins]: <HandCoinsIcon />,
  [ICONS.piggy_bank]: <PiggyBankIcon />,
  [ICONS.wallet_card]: <WalletCardsIcon />,
  [ICONS.wallet_minimal]: <WalletMinimalIcon />,
  [ICONS.car_front]: <CarFrontIcon />,
  [ICONS.car_taxi_front]: <CarTaxiFrontIcon />,
  [ICONS.ambulance]: <AmbulanceIcon />,
  [ICONS.cross]: <CrossIcon />,
  [ICONS.hospital]: <HospitalIcon />,
  [ICONS.bandage]: <BandageIcon />,
  [ICONS.heart_pulse]: <HeartPulseIcon />,
  [ICONS.bone]: <BoneIcon />,
  [ICONS.brain]: <BrainIcon />,
  [ICONS.graduation_cap]: <GraduationCapIcon />,
  [ICONS.dices]: <DicesIcon />,
  [ICONS.school]: <SchoolIcon />,
  [ICONS.bitcoin]: <BitcoinIcon />,
  [ICONS.target]: <TargetIcon />,
  [ICONS.trophy]: <TrophyIcon />,
  [ICONS.book]: <BookIcon />,
  [ICONS.book_open]: <BookOpenIcon />,
  [ICONS.bookmark]: <BookmarkIcon />,
  [ICONS.notebook]: <NotebookIcon />,
  [ICONS.ticket]: <TicketIcon />,
  [ICONS.tag]: <TagIcon />,
  [ICONS.tickets]: <TicketsIcon />,
  [ICONS.fence]: <FenceIcon />,
  [ICONS.train_front]: <TrainFrontIcon />,
  [ICONS.tv]: <TvIcon />,
  [ICONS.cigarette]: <CigaretteIcon />,
  [ICONS.circle_parking]: <CircleParkingIcon />,
  [ICONS.container]: <ContainerIcon />,
  [ICONS.fuel]: <FuelIcon />,
  [ICONS.luggage]: <LuggageIcon />,
  [ICONS.plane]: <PlaneIcon />,
  [ICONS.ship]: <ShipIcon />,
  [ICONS.briefcase]: <BriefcaseIcon />,
  [ICONS.clapperboard]: <ClapperboardIcon />,
  [ICONS.film]: <FilmIcon />,
  [ICONS.popcorn]: <PopcornIcon />,
  [ICONS.dumbbell]: <DumbbellIcon />,
  [ICONS.biceps_flexed]: <BicepsFlexedIcon />,
  [ICONS.mic_vocal]: <MicVocalIcon />,
  [ICONS.piano]: <PianoIcon />,
  [ICONS.headphones]: <HeadphonesIcon />,
  [ICONS.computer]: <ComputerIcon />,
  [ICONS.binary]: <BinaryIcon />,
  [ICONS.cable]: <CableIcon />,
  [ICONS.cpu]: <CpuIcon />,
  [ICONS.laptop]: <LaptopIcon />,
  [ICONS.pc_case]: <PcCaseIcon />,
  [ICONS.router]: <RouterIcon />,
  [ICONS.phone]: <PhoneIcon />,
  [ICONS.smartphone]: <SmartphoneIcon />,
  [ICONS.stethoscope]: <StethoscopeIcon />,
  [ICONS.utility_pole]: <UtilityPoleIcon />,
  [ICONS.megaphone]: <MegaphoneIcon />,
  [ICONS.ethernet_port]: <EthernetPortIcon />,
  [ICONS.earth]: <EarthIcon />,
  [ICONS.globe]: <GlobeIcon />,
  [ICONS.shield]: <ShieldIcon />,
  [ICONS.volleyball]: <VolleyballIcon />,
  [ICONS.ruler]: <RulerIcon />,
  [ICONS.calculator]: <CalculatorIcon />,
  [ICONS.music]: <MusicIcon />,
  [ICONS.drum]: <DrumIcon />,
  [ICONS.theater]: <TheaterIcon />,
  [ICONS.shopping_bag]: <ShoppingBagIcon />,
  [ICONS.shopping_basket]: <ShoppingBasketIcon />,
  [ICONS.shopping_cart]: <ShoppingCartIcon />,
  [ICONS.barcode]: <BarcodeIcon />,
  [ICONS.shirt]: <ShirtIcon />,
  [ICONS.tent_tree]: <TentTreeIcon />,
  [ICONS.utensils]: <UtensilsIcon />,
  [ICONS.shower_head]: <ShowerHeadIcon />,
  [ICONS.washing_machine]: <WashingMachineIcon />,
  [ICONS.bed_single]: <BedSingleIcon />,
  [ICONS.bed_double]: <BedDoubleIcon />,
  [ICONS.bus_front]: <BusFrontIcon />,
  [ICONS.pill]: <PillIcon />,
  [ICONS.syringe]: <SyringeIcon />,
  [ICONS.microscope]: <MicroscopeIcon />,
  [ICONS.siren]: <SirenIcon />,
  [ICONS.zap]: <ZapIcon />,
  [ICONS.heater]: <HeaterIcon />,
  [ICONS.battery_charging]: <BatteryChargingIcon />,
  [ICONS.user]: <UserIcon />,
  [ICONS.venetian_mask]: <VenetianMaskIcon />,
  [ICONS.house]: <HouseIcon />,
  [ICONS.hammer]: <HammerIcon />,
  [ICONS.microwave]: <MicrowaveIcon />,
  [ICONS.paint_roller]: <PaintRollerIcon />,
  [ICONS.paintbrush_vertical]: <PaintbrushVerticalIcon />,
  [ICONS.tv_minimal_play]: <TvMinimalPlayIcon />,
  [ICONS.wine]: <WineIcon />,
  [ICONS.medal]: <MedalIcon />,
  [ICONS.crown]: <CrownIcon />,
  [ICONS.milk]: <MilkIcon />,
  [ICONS.glass_water]: <GlassWaterIcon />,
  [ICONS.droplet]: <DropletIcon />,
  [ICONS.hand_platter]: <HandPlatterIcon />,
  [ICONS.fire_extinguisher]: <FireExtinguisherIcon />,
  [ICONS.package]: <PackageIcon />,
  [ICONS.armchair]: <ArmchairIcon />,
  [ICONS.at_sign]: <AtSignIcon />,
  [ICONS.cake]: <CakeIcon />,
  [ICONS.building]: <BuildingIcon />,
  [ICONS.cog]: <CogIcon />,
  [ICONS.id_card]: <IdCardIcon />,
  [ICONS.mail]: <MailIcon />,
  [ICONS.search]: <SearchIcon />,
  [ICONS.binoculars]: <BinocularsIcon />,
  [ICONS.tree_palm]: <TreePalmIcon />,
  [ICONS.trees]: <TreesIcon />,
  [ICONS.flower]: <FlowerIcon />,
  [ICONS.dog]: <DogIcon />,
  [ICONS.paw_print]: <PawPrintIcon />,
  [ICONS.cat]: <CatIcon />,
  [ICONS.fish]: <FishIcon />,
  [ICONS.bird]: <BirdIcon />,
  [ICONS.ice_cream_cone]: <IceCreamConeIcon />,
  [ICONS.beef]: <BeefIcon />,
  [ICONS.pizza]: <PizzaIcon />,
  [ICONS.apple]: <AppleIcon />,
  [ICONS.bean]: <BeanIcon />,
  [ICONS.drumstick]: <DrumstickIcon />,
  [ICONS.salad]: <SaladIcon />,
  [ICONS.sandwich]: <SandwichIcon />,
  [ICONS.bike]: <BikeIcon />,
  [ICONS.coins]: <CoinsIcon />,
  [ICONS.gamepad]: <GamepadIcon />,
  [ICONS.skull]: <SkullIcon />,
  [ICONS.sword]: <SwordIcon />,
  [ICONS.bell_electric]: <BellElectricIcon />,
  [ICONS.heart]: <HeartIcon />,
  [ICONS.clover]: <CloverIcon />,
  [ICONS.monitor_play]: <MonitorPlayIcon />,
  [ICONS.glasses]: <GlassesIcon />,
  [ICONS.key_round]: <KeyRoundIcon />,
  [ICONS.candy]: <CandyIcon />,
  [ICONS.baby]: <BabyIcon />
}