import {
  AmbulanceIcon,
  BandageIcon,
  BanknoteIcon,
  BarcodeIcon,
  BicepsFlexedIcon,
  BinaryIcon,
  BitcoinIcon,
  BoneIcon,
  BookIcon,
  BookmarkIcon,
  BookOpenIcon,
  BrainIcon,
  BriefcaseIcon,
  CableIcon,
  CalculatorIcon,
  CarFrontIcon,
  CarTaxiFrontIcon,
  CigaretteIcon,
  CircleParkingIcon,
  ClapperboardIcon,
  ComputerIcon,
  ContainerIcon,
  CpuIcon,
  CreditCardIcon,
  CrossIcon,
  DicesIcon,
  DrumIcon,
  DumbbellIcon,
  EarthIcon,
  EthernetPortIcon,
  FenceIcon,
  FilmIcon,
  FuelIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HeadphonesIcon,
  HeartPulseIcon,
  HospitalIcon,
  LandmarkIcon,
  LaptopIcon,
  LuggageIcon,
  MegaphoneIcon,
  MicVocalIcon,
  MusicIcon,
  NotebookIcon,
  PcCaseIcon,
  PhoneIcon,
  PianoIcon,
  PiggyBankIcon,
  PlaneIcon,
  PopcornIcon,
  RouterIcon,
  RulerIcon,
  SchoolIcon,
  ShieldIcon,
  ShipIcon,
  ShoppingBagIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  StethoscopeIcon,
  TagIcon,
  TargetIcon,
  TheaterIcon,
  TicketIcon,
  TicketsIcon,
  TrainFrontIcon,
  TrophyIcon,
  TvIcon,
  UtilityPoleIcon,
  VaultIcon,
  VolleyballIcon,
  WalletCardsIcon,
  WalletMinimalIcon
} from "lucide-react";
import { ICONS } from "~/shared/types/icon";

export const icons = {
  [ICONS.credit_card]: <CreditCardIcon />,
  [ICONS.landmark]: <LandmarkIcon />,
  [ICONS.vault]: <VaultIcon />,
  [ICONS.banknote]: <BanknoteIcon />,
  [ICONS.hand_coins]: <HandCoinsIcon />,
  [ICONS.piggy_bank]: <PiggyBankIcon />,
  [ICONS.wallet_card]: <WalletCardsIcon />,
  [ICONS.wallet_minimal]: <WalletMinimalIcon />,
  [ICONS.car_front]: <CarFrontIcon />,
  [ICONS.car_taxi_front]: <CarTaxiFrontIcon />,
  [ICONS.ambulance]: <AmbulanceIcon />,
  [ICONS.cross]: <CrossIcon />,
  [ICONS.hospital]: <HospitalIcon />,
  [ICONS.bandage]: <BandageIcon />,
  [ICONS.heart_pulse]: <HeartPulseIcon />,
  [ICONS.bone]: <BoneIcon />,
  [ICONS.brain]: <BrainIcon />,
  [ICONS.graduation_cap]: <GraduationCapIcon />,
  [ICONS.dices]: <DicesIcon />,
  [ICONS.school]: <SchoolIcon />,
  [ICONS.bitcoin]: <BitcoinIcon />,
  [ICONS.target]: <TargetIcon />,
  [ICONS.trophy]: <TrophyIcon />,
  [ICONS.book]: <BookIcon />,
  [ICONS.book_open]: <BookOpenIcon />,
  [ICONS.bookmark]: <BookmarkIcon />,
  [ICONS.notebook]: <NotebookIcon />,
  [ICONS.ticket]: <TicketIcon />,
  [ICONS.tag]: <TagIcon />,
  [ICONS.tickets]: <TicketsIcon />,
  [ICONS.fence]: <FenceIcon />,
  [ICONS.train_front]: <TrainFrontIcon />,
  [ICONS.tv]: <TvIcon />,
  [ICONS.cigarette]: <CigaretteIcon />,
  [ICONS.circle_parking]: <CircleParkingIcon />,
  [ICONS.container]: <ContainerIcon />,
  [ICONS.fuel]: <FuelIcon />,
  [ICONS.luggage]: <LuggageIcon />,
  [ICONS.plane]: <PlaneIcon />,
  [ICONS.ship]: <ShipIcon />,
  [ICONS.briefcase]: <BriefcaseIcon />,
  [ICONS.clapperboard]: <ClapperboardIcon />,
  [ICONS.film]: <FilmIcon />,
  [ICONS.popcorn]: <PopcornIcon />,
  [ICONS.dumbbell]: <DumbbellIcon />,
  [ICONS.biceps_flexed]: <BicepsFlexedIcon />,
  [ICONS.mic_vocal]: <MicVocalIcon />,
  [ICONS.piano]: <PianoIcon />,
  [ICONS.headphones]: <HeadphonesIcon />,
  [ICONS.computer]: <ComputerIcon />,
  [ICONS.binary]: <BinaryIcon />,
  [ICONS.cable]: <CableIcon />,
  [ICONS.cpu]: <CpuIcon />,
  [ICONS.laptop]: <LaptopIcon />,
  [ICONS.pc_case]: <PcCaseIcon />,
  [ICONS.router]: <RouterIcon />,
  [ICONS.phone]: <PhoneIcon />,
  [ICONS.smartphone]: <SmartphoneIcon />,
  [ICONS.stethoscope]: <StethoscopeIcon />,
  [ICONS.utility_pole]: <UtilityPoleIcon />,
  [ICONS.megaphone]: <MegaphoneIcon />,
  [ICONS.ethernet_port]: <EthernetPortIcon />,
  [ICONS.earth]: <EarthIcon />,
  [ICONS.globe]: <GlobeIcon />,
  [ICONS.shield]: <ShieldIcon />,
  [ICONS.volleyball]: <VolleyballIcon />,
  [ICONS.ruler]: <RulerIcon />,
  [ICONS.calculator]: <CalculatorIcon />,
  [ICONS.music]: <MusicIcon />,
  [ICONS.drum]: <DrumIcon />,
  [ICONS.theater]: <TheaterIcon />,
  [ICONS.shopping_bag]: <ShoppingBagIcon />,
  [ICONS.shopping_basket]: <ShoppingBasketIcon />,
  [ICONS.shopping_cart]: <ShoppingCartIcon />,
  [ICONS.barcode]: <BarcodeIcon />,
  [ICONS.shirt]: <></>,
  [ICONS.tent_tree]: <></>,
  [ICONS.utensils]: <></>,
  [ICONS.shower_head]: <></>,
  [ICONS.washing_machine]: <></>,
  [ICONS.bed_single]: <></>,
  [ICONS.bed_double]: <></>,
  [ICONS.bus_front]: <></>,
  [ICONS.pill]: <></>,
  [ICONS.syringe]: <></>,
  [ICONS.microscope]: <></>,
  [ICONS.siren]: <></>,
  [ICONS.zap]: <></>,
  [ICONS.heater]: <></>,
  [ICONS.battery_charging]: <></>,
  [ICONS.user]: <></>,
  [ICONS.venetian_mask]: <></>,
  [ICONS.house]: <></>,
  [ICONS.hammer]: <></>,
  [ICONS.microwave]: <></>,
  [ICONS.paint_roller]: <></>,
  [ICONS.paintbrush_vertical]: <></>,
  [ICONS.tv_minimal_play]: <></>,
  [ICONS.wine]: <></>,
  [ICONS.medal]: <></>,
  [ICONS.crown]: <></>,
  [ICONS.milk]: <></>,
  [ICONS.glass_water]: <></>,
  [ICONS.droplet]: <></>,
  [ICONS.hand_platter]: <></>,
  [ICONS.fire_extinguisher]: <></>,
  [ICONS.package]: <></>,
  [ICONS.armchair]: <></>,
  [ICONS.at_sign]: <></>,
  [ICONS.cake]: <></>,
  [ICONS.building]: <></>,
  [ICONS.cog]: <></>,
  [ICONS.id_card]: <></>,
  [ICONS.mail]: <></>,
  [ICONS.search]: <></>,
  [ICONS.binoculars]: <></>,
  [ICONS.tree_palm]: <></>,
  [ICONS.trees]: <></>,
  [ICONS.flower]: <></>,
  [ICONS.dog]: <></>,
  [ICONS.paw_print]: <></>,
  [ICONS.cat]: <></>,
  [ICONS.fish]: <></>,
  [ICONS.bird]: <></>,
  [ICONS.ice_cream_cone]: <></>,
  [ICONS.beef]: <></>,
  [ICONS.pizza]: <></>,
  [ICONS.apple]: <></>,
  [ICONS.bean]: <></>,
  [ICONS.drumstick]: <></>,
  [ICONS.salad]: <></>,
  [ICONS.sandwich]: <></>,
  [ICONS.bike]: <></>,
  [ICONS.coins]: <></>,
  [ICONS.gamepad]: <></>,
  [ICONS.skull]: <></>,
  [ICONS.sword]: <></>,
  [ICONS.bell_electric]: <></>,
  [ICONS.heart]: <></>,
  [ICONS.clover]: <></>,
  [ICONS.monitor_play]: <></>,
  [ICONS.glasses]: <></>,
  [ICONS.key_round]: <></>,
  [ICONS.candy]: <></>,
  [ICONS.baby]: <></>
}