export const ICONS = {
  "credit-card": "credit-card",
  "landmark": "landmark",
  "vault": "vault",
  "banknote": "banknote",
  "hand-coins": "hand-coins",
  "piggy-bank": "piggy-bank",
  "wallet-cards": "wallet-cards",
  "wallet-minimal": "wallet-minimal",
  "car-front": "car-front",
  "car-taxi-front": "car-taxi-front",
  "ambulance": "ambulance",
  "cross": "cross",
  "hospital": "hospital",
  "bandage": "bandage",
  "heart-pulse": "heart-pulse",
  "bone": "bone",
  "brain": "brain",
  "graduation-cap": "graduation-cap",
  "dices": "dices",
  "school": "school",
  "bitcoin": "bitcoin",
  "target": "target",
  "trophy": "trophy",
  "book": "book",
  "book-open": "book-open",
  "bookmark": "bookmark",
  "notebook": "notebook",
  "ticket": "ticket",
  "tag": "tag",
  "tickets": "tickets",
  "fence": "fence",
  "train-front": "train-front",
  "tv": "tv",
  "cigarette": "cigarette",
  "circle-parking": "circle-parking",
  "container": "container",
  "fuel": "fuel",
  "luggage": "luggage",
  "plane": "plane",
  "ship": "ship",
  "briefcase": "briefcase",
  "clapperboard": "clapperboard",
  "film": "film",
  "popcorn": "popcorn",
  "dumbbell": "dumbbell",
  "biceps-flexed": "biceps-flexed",
  "mic-vocal": "mic-vocal",
  "piano": "piano",
  "headphones": "headphones",
  "computer": "computer",
  "binary": "binary",
  "cable": "cable",
  "cpu": "cpu",
  "laptop": "laptop",
  "pc-case": "pc-case",
  "router": "router",
  "phone": "phone",
  "smartphone": "smartphone",
  "stethoscope": "stethoscope",
  "utility-pole": "utility-pole",
  "megaphone": "megaphone",
  "ethernet-port": "ethernet-port",
  "earth": "earth",
  "globe": "globe",
  "shield": "shield",
  "volleyball": "volleyball",
  "ruler": "ruler",
  "calculator": "calculator",
  "music": "music",
  "drum": "drum",
  "theater": "theater",
  "shopping-bag": "shopping-bag",
  "shopping-basket": "shopping-basket",
  "shopping-cart": "shopping-cart",
  "barcode": "barcode",
  "shirt": "shirt",
  "tent-tree": "tent-tree",
  "utensils": "utensils",
  "shower-head": "shower-head",
  "washing-machine": "washing-machine",
  "bed-single": "bed-single",
  "bed-double": "bed-double",
  "bus-front": "bus-front",
  "pill": "pill",
  "syringe": "syringe",
  "microscope": "microscope",
  "siren": "siren",
  "zap": "zap",
  "heater": "heater",
  "battery-charging": "battery-charging",
  "user": "user",
  "venetian-mask": "venetian-mask",
  "house": "house",
  "hammer": "hammer",
  "microwave": "microwave",
  "paint-roller": "paint-roller",
  "paintbrush-vertical": "paintbrush-vertical",
  "tv-minimal-play": "tv-minimal-play",
  "wine": "wine",
  "medal": "medal",
  "crown": "crown",
  "milk": "milk",
  "glass-water": "glass-water",
  "droplet": "droplet",
  "hand-platter": "hand-platter",
  "fire-extinguisher": "fire-extinguisher",
  "package": "package",
  "armchair": "armchair",
  "at-sign": "at-sign",
  "cake": "cake",
  "building": "building",
  "cog": "cog",
  "id-card": "id-card",
  "mail": "mail",
  "search": "search",
  "binoculars": "binoculars",
  "tree-palm": "tree-palm",
  "trees": "trees",
  "flower": "flower",
  "dog": "dog",
  "paw-print": "paw-print",
  "cat": "cat",
  "fish": "fish",
  "bird": "bird",
  "ice-cream-cone": "ice-cream-cone",
  "beef": "beef",
  "pizza": "pizza",
  "apple": "apple",
  "bean": "bean",
  "drumstick": "drumstick",
  "salad": "salad",
  "sandwich": "sandwich",
  "bike": "bike",
  "coins": "coins",
  "gamepad": "gamepad",
  "skull": "skull",
  "sword": "sword",
  "bell-electric": "bell-electric",
  "heart": "heart",
  "clover": "clover",
  "monitor-play": "monitor-play",
  "glasses": "glasses",
  "key-round": "key-round",
  "candy": "candy",
  "baby": "baby"
} as const

export type Icons = typeof ICONS

export type Icon =
  Icons["credit-card"] |
  Icons["landmark"] |
  Icons["vault"] |
  Icons["banknote"] |
  Icons["hand-coins"] |
  Icons["piggy-bank"] |
  Icons["wallet-cards"] |
  Icons["wallet-minimal"] |
  Icons["car-front"] |
  Icons["car-taxi-front"] |
  Icons["ambulance"] |
  Icons["cross"] |
  Icons["hospital"] |
  Icons["bandage"] |
  Icons["heart-pulse"] |
  Icons["bone"] |
  Icons["brain"] |
  Icons["graduation-cap"] |
  Icons["dices"] |
  Icons["school"] |
  Icons["bitcoin"] |
  Icons["target"] |
  Icons["trophy"] |
  Icons["book"] |
  Icons["book-open"] |
  Icons["bookmark"] |
  Icons["notebook"] |
  Icons["ticket"] |
  Icons["tag"] |
  Icons["tickets"] |
  Icons["fence"] |
  Icons["train-front"] |
  Icons["tv"] |
  Icons["cigarette"] |
  Icons["circle-parking"] |
  Icons["container"] |
  Icons["fuel"] |
  Icons["luggage"] |
  Icons["plane"] |
  Icons["ship"] |
  Icons["briefcase"] |
  Icons["clapperboard"] |
  Icons["film"] |
  Icons["popcorn"] |
  Icons["dumbbell"] |
  Icons["biceps-flexed"] |
  Icons["mic-vocal"] |
  Icons["piano"] |
  Icons["headphones"] |
  Icons["computer"] |
  Icons["binary"] |
  Icons["cable"] |
  Icons["cpu"] |
  Icons["laptop"] |
  Icons["pc-case"] |
  Icons["router"] |
  Icons["phone"] |
  Icons["smartphone"] |
  Icons["stethoscope"] |
  Icons["utility-pole"] |
  Icons["megaphone"] |
  Icons["ethernet-port"] |
  Icons["earth"] |
  Icons["globe"] |
  Icons["shield"] |
  Icons["volleyball"] |
  Icons["ruler"] |
  Icons["calculator"] |
  Icons["music"] |
  Icons["drum"] |
  Icons["theater"] |
  Icons["shopping-bag"] |
  Icons["shopping-basket"] |
  Icons["shopping-cart"] |
  Icons["barcode"] |
  Icons["shirt"] |
  Icons["tent-tree"] |
  Icons["utensils"] |
  Icons["shower-head"] |
  Icons["washing-machine"] |
  Icons["bed-single"] |
  Icons["bed-double"] |
  Icons["bus-front"] |
  Icons["pill"] |
  Icons["syringe"] |
  Icons["microscope"] |
  Icons["siren"] |
  Icons["zap"] |
  Icons["heater"] |
  Icons["battery-charging"] |
  Icons["user"] |
  Icons["venetian-mask"] |
  Icons["house"] |
  Icons["hammer"] |
  Icons["microwave"] |
  Icons["paint-roller"] |
  Icons["paintbrush-vertical"] |
  Icons["tv-minimal-play"] |
  Icons["wine"] |
  Icons["medal"] |
  Icons["crown"] |
  Icons["milk"] |
  Icons["glass-water"] |
  Icons["droplet"] |
  Icons["hand-platter"] |
  Icons["fire-extinguisher"] |
  Icons["package"] |
  Icons["armchair"] |
  Icons["at-sign"] |
  Icons["cake"] |
  Icons["building"] |
  Icons["cog"] |
  Icons["id-card"] |
  Icons["mail"] |
  Icons["search"] |
  Icons["binoculars"] |
  Icons["tree-palm"] |
  Icons["trees"] |
  Icons["flower"] |
  Icons["dog"] |
  Icons["paw-print"] |
  Icons["cat"] |
  Icons["fish"] |
  Icons["bird"] |
  Icons["ice-cream-cone"] |
  Icons["beef"] |
  Icons["pizza"] |
  Icons["apple"] |
  Icons["bean"] |
  Icons["drumstick"] |
  Icons["salad"] |
  Icons["sandwich"] |
  Icons["bike"] |
  Icons["coins"] |
  Icons["gamepad"] |
  Icons["skull"] |
  Icons["sword"] |
  Icons["bell-electric"] |
  Icons["heart"] |
  Icons["clover"] |
  Icons["monitor-play"] |
  Icons["glasses"] |
  Icons["key-round"] |
  Icons["candy"] |
  Icons["baby"]
