name: CI/CD
on: [push]

jobs:
  webapp-code-health:
    name: Code Health (Webapp)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run -w webapp typecheck

      - name: Lint
        run: npm run -w webapp lint